### ISSUE TITLE
Font Choice 4 - Modak

### ISSUE THREAD

**Issue by th1095l** [th1095l/Python-Planning#10]
The fourth font choice for the application, the font Modak.
[Preview](https://github.com/th1095l/Python-Planning/blob/436f9fb1f9ac270050fa322ddc036d9d6b077899/modak_font_preview.png)
This fourth font was not chosen as it does not professional in its design, and would not fit on a biology-themed quiz, which would be more centered around a sleek, minimalistic appearance.

**Comment by BrandonHuang2** [comment]
Man, this font is pretty bad, please don't use this font.
