### ISSUE TITLE
Font Choice 5 - Inconsolata

### ISSUE THREAD

**Issue by th1095l** [th1095l/Python-Planning#11]
The fifth font choice for the application, the font Inconsolata.
[Preview](https://github.com/th1095l/Python-Planning/blob/436f9fb1f9ac270050fa322ddc036d9d6b077899/inconsolata_font_preview.png)
This font was not chosen as it did not fit the theme of Biology well, although it was sans serif. The tall typeface it presents would not fit with any of the other font choices, as well as cause it to appear out of place with the rest of the application.

**Comment by BrandonHuang2** [comment]
This one looks too unnatural, something more natural would be nicer, or softer.
