### ISSUE TITLE
Color Palette Design Choice 1

### ISSUE THREAD

**Issue by th1095l** [th1095l/Python-Planning#5]
[[Source]](https://github.com/th1095l/Python-Planning/blob/master/Color_Palette_1.PNG)
This is the first of 2 choices for the color palette to base the entire aesthetic design of the application on.
This choice of color palette includes blue shades as well as dark shades which would be able to fit well with a more modern, sleek theme, as well as present science-related material in a representational manner.

**Comment by BrandonHuang2** [comment]
I like the darkness of this palette, it's cooler than the other.
