### ISSUE TITLE
Font Choice 1 - Roboto

### ISSUE THREAD

**Issue by th1095l** [th1095l/Python-Planning#7]
The first choice for font design, the Roboto font.
[Preview](https://github.com/th1095l/Python-Planning/blob/436f9fb1f9ac270050fa322ddc036d9d6b077899/roboto_font_preview.png)
This font was a suitable candidate, due to its sans-serif typeface and clean look. However, it was ultimately decided against using this font as it is now becoming more overused in general applications, therefore potentially causing the application to lose its appeal as something original.

**Comment by BrandonHuang2** [comment]
I think this design looks okay, good enough.
