### ISSUE TITLE
Font Choice 3 - Nunito

### ISSUE THREAD

**Issue by th1095l** [th1095l/Python-Planning#9]
The third font choice for the application, the font Nunito.
[Preview](https://github.com/th1095l/Python-Planning/blob/436f9fb1f9ac270050fa322ddc036d9d6b077899/nunito_font_preview.png)
This font choice was also chosen for the headings and misc. text of the application, as it would look appealing with a larger weight, and would also pair well with the Mukta font, thus keeping a sleek design for the application.

**Comment by BrandonHuang2** [comment]
This font kind of looks boring to me, but it's not meant to stand out anyway so it's good.
